#!/bin/bash

# Function to display error messages and exit
fatal() {
    echo "Error: $1" >&2
    exit 1
}

# Check for correct usage
if [ $# -gt 1 ]; then
    fatal 'Incorrect usage, too many arguments. Use: git sync [-i]'
fi

# Handle interactive flag
interactive=false
if [ $# -eq 1 ]; then
    if [ "$1" == "-i" ]; then
        interactive=true
    else
        fatal "Incorrect usage, unexpected argument to git sync: \"$1\""
    fi
fi

# Check for uncommitted changes
if [[ $(git status --porcelain) ]]; then
    fatal "You have uncommitted changes, proceeding automatically would be dangerous."
fi

# Get current branch name
initial_branch=$(git branch --show-current)

# Update the main branch
main_branch=$(git remote show origin | sed -n '/HEAD branch/s/.*: //p')
echo "Switching to $main_branch branch"
git checkout "$main_branch"
git pull origin "$main_branch"
git checkout "$initial_branch"

# Rebase onto the main branch
echo "Rebasing $initial_branch on $main_branch"
if $interactive; then
    git rebase -i "$main_branch"
else
    git rebase "$main_branch"
fi

echo "$initial_branch synced with origin, $main_branch rebased"
